import cohere

# The Memomaster-Original Prototype Release by Dario Gerald

# Variables
API_KEY = '976IfwjgthQ17l0iRDYLLnkwr90YxVNdCSCxltzV'
co = cohere.Client(API_KEY) # REMOVE LATER

# To Begin with, we have an introduction for the user:
print("Welcome to The MemoMaster original prototype. It is simply a CLI version of what will be a bigger project in the future if time permits. To begin with enter your Cohere API in the `main.py` file, and place all of your information in `text.txt`. However, keep in mind, you can only do it once at a time (one note). For example, if you took notes on Biology and Economics, only put one of the notes at a time, otherwise, it may not work.")
print("\n" * 5)

condition = "You are CoherAI. After this piece of information, you will be given a block of text. Your task is to convert it into a question and answer format for the user to use as a 'flashcard'. Make them concise and bite-sized for easy understanding. They will be used for Anki flashcards."

file_path = "text.txt" 
with open(file_path, 'r', encoding='utf-8') as file:
    info = file.read()

final = condition + "\n\nThe information goes as follows: " + info

def chat_with_cohere(prompt):
    response = co.generate(
        model='command-r-plus',  # You can select different model sizes if you want
        prompt=prompt,
        max_tokens=1000,
        temperature=0.7
    )
    return response.generations[0].text.strip()


def main():
    while True:
        if info == "":
            print("Invalid information. Error code 201: No information in `text.txt`.")
            break
        elif API_KEY == 'ENTER YOUR API KEY HERE!!!!':
            print("Invalid information. Error code 202: Invalid API Key. Please update it.")
            break
        else:
            response = chat_with_cohere(final)
            print(response)

        print("\n" * 3)
        print("Keep in mind, some information generated by AI may be incorrect, offensive or harmful. Please keep that in mind. Thank you for using the product, made by Dario Gerald :]")

        something = input("Enter something to exit the program. If you wish to make more flashcards, exit the program and enter once again: ")
        break




if __name__ == "__main__":
    main()